###############################################################################
#
# Top level makefile. Forwards $(MAKE) calls to $(SUBDIRS) subdirectories.
#
# Author: 	Alif Ahmed
# email: 	alifahmed@virginia.edu
# Updated: 	Aug 06, 2019
#
###############################################################################

SUBDIRS = gather openmp rand scatter scatter_gather select_func seq

include makedir.mk


