###############################################################################
#
# Top level makefile. Forwards $(MAKE) calls to $(TARGETS) subdirectories.
#
# Author: 	Alif Ahmed
# email: 	alifahmed@virginia.edu
# Updated: 	Aug 06, 2019
#
###############################################################################

TARGETS = 1_roofline

include ../makedir.mk

