###############################################################################
#
# Top level makefile. Forwards $(MAKE) calls to $(SUBDIRS) subdirectories.
#
# Author: 	Alif Ahmed
# email: 	alifahmed@virginia.edu
# Updated: 	Aug 06, 2019
#
###############################################################################

SUBDIRS = 	1_bandwidth_test    \
			2_bandwidth 		\
			3_latency			\
			4_cache

include ../makedir.mk

