###############################################################################
#
# Top level makefile. Forwards $(MAKE) calls to $(TARGETS) subdirectories.
#
# Author: 	Alif Ahmed
# email: 	alifahmed@virginia.edu
# Updated: 	Aug 06, 2019
#
###############################################################################

TARGETS = 	1_roofline 			\
			2_bandwidth 		\
			3_latency			\
			4_cache

include ../makedir.mk

